configs:
  secret:
    argocdServerAdminPassword: '$2a$10$9BU9yDBq.ULIAEW9uJB86.da4lGI7cehqjBziOYcOUolQRUGJFYcW'

  repositories:
    camel-k:
      name: camel-k
      type: git
      url: https://apache.github.io/camel-k/charts/

server:
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
