{{- if .Values.camelK }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camelk
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: camel-k
    repoURL: https://apache.github.io/camel-k/charts/
    targetRevision: 0.12.1
  destination:
    name: in-cluster
    namespace: camelk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}