{{- if .Values.camelK }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: camel-k
    repoURL: https://apache.github.io/camel-k/charts/
    targetRevision: 0.12.1
    helm:
      values: |
        platform:
          build:
            registry:
              address: 10.107.206.67
              insecure: true
  destination:
    name: in-cluster
    namespace: camelk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}